version = 1

# PHP Analyzer
[[analyzers]]
name = "php"
enabled = true
php_version = "8.1"  # Adjust this to your project's PHP version

# JavaScript/React Analyzer
[[analyzers]]
name = "javascript"
enabled = true
node_version = "16"  # Adjust this to your project's Node.js version